frontend/README.md, mysql/README.md, postman/README.md, src/requirements.txt
Habe die grundlegende Struktur aufgesetzt.
=> feat: created basic directory structure

src/server/bo/Person.py
Review für Klassenstruktur von Person
=> Klasse person mo

src/server/bo/BusinessObject.py, src/server/bo/Konversation.py, src/server/bo/Lerngruppe.py, src/server/bo/Nachricht.py
=> Bo+klassen a

src/server/bo/Lernvorliebe.py, src/server/bo/Lernvorlieben.py, src/server/bo/Profil.py, src/server/bo/Vorschlag.py
Klassen Profil, Lernvorlieben und Vorschlag für den Review
=> Klassen bo leo

mysql/MySQL-Dump_Test.sql, src/server/db/Mapper.py, src/server/db/NachrichtMapper.py
SQL Test Dump erstellt: Database "testproject" mit nachrichten und personen Tables.
Mapper.py implementiert
NachrichtMapper.py implementiert
=> Mapper andi

src/SecurityDecorator.py
Noch unfertig, da admin Klasse nicht existiert.
=> feat: SecurityDecorator.py implementiert/need fixes

src/main.py
Großen init-Kommentar entfernt: Anleitung für rudimentäre API (redundant)
=> refactor: deleted multi-line comment (initial api)

src/server/db/PersonMapper.py
=> fix: PersonMapper.py SQL statements angepasst

src/server/db/KonversationMapper.py
Habe den Konversationsmapper erstellt.
einziges problem: gibt beim test objekt None zurück (Zeile 163 ff.) - muss das so sein?
=> feat: created Konversationmapper.py and added local tests

src/server/db/ProfilMapper.py
ProfilMapper.py fertiggestellt
=> feat: ProfilMapper.py

src/server/Admin.py, src/server/db/ProfilMapper.py
=> feat: Admin.py Profil und PartnerVorschlag implementiert

src/server/db/LerngruppeMapper.py
Changes in der update Methode und Testing
=> fix: LerngruppeMapper

src/main.py
models ergänzt.
naming: Sollen wir es Lernvorlieben (wie in db) oder Lernvorliebe (wie in Lernvorliebe.py) nennen?
=> feat: added Lernvorliebe and Konversation models in main.py

src/main.py
Die Hauptänderungen befinden sich in den (neuen) Zeilen 82-88. Das andere sind nur Fixes und erweitertes Commenting.
Bitte um Freigabe :)
=> feat: Erstellung api.inherit in main.py für Lerngruppe

src/main.py
=> feat: BO Person + API Route implementiert

src/main.py, src/server/Admin.py, src/server/bo/Nachricht.py
=> Api nachricht

src/main.py
PersonOperations und PersonListOperations hinzugefügt
=> Moritz ops

frontend/src/api/PersonBO.js
=> fix: PersonBO.js Constructor

frontend/src/api/ChatTeilnahme.js, frontend/src/api/PartnerVorschlag.js, frontend/src/api/file.txt
toString() und fromJSON() abklären
=> feat: ChatTeilnahme.js und PartnerVorschlag.js definiert

frontend/src/api/LerngruppeBO.js, src/main.py
Habe die Api Routes /lerngruppen und /lerngruppe/<int:id> in main.py angelegt
=> feat: Api Routes /lerngruppen und /lerngruppe/<int:id> fertiggestellt

src/main.py
POST-Method in List Operations oder in Single Operations?
=> feat: completed Konversation and Nachricht Operations in main.py

frontend/src/api/NachrichtBO.js, frontend/src/api/PersonBO.js, frontend/src/api/ProfilBO.js
=> feat: Nachricht.BO und Profil.BO

frontend/src/api/LernvorliebeBO.js, src/main.py
fix: LernvorliebeBO.js changing one parameter
=> add: main.py Profil Operations

frontend/package.json, frontend/src/App.js, frontend/src/api/ChatTeilnahmeBO.js, frontend/src/api/GruppenTeilnahmeBO.js, frontend/src/api/KonversationBO.js, frontend/src/api/LerngruppeBO.js, frontend/src/api/PersonBO.js, frontend/src/api/StudooAPI.js, frontend/src/api/VorschlagBO.js, frontend/src/api/index.js, frontend/src/components/LerngruppeListEntry.js, frontend/src/components/LerngruppenList.js, frontend/src/components/PersonListEntry.js, frontend/src/components/PersonenList.js, frontend/src/components/TestList.js, frontend/src/components/TestListEntry.js, frontend/src/components/dialogs/ContextErrorMessage.js, frontend/src/components/dialogs/LoadingProgress.js, frontend/src/components/dialogs/PersonDeleteDialog.js, frontend/src/components/dialogs/PersonForm.js, frontend/src/index.js, src/main.py
Lerngruppen anzeigen mit TestList und TestListEntry
=> Andi frontend

frontend/src/App.js, frontend/src/api/StudooAPI.js, frontend/src/components/PersonListEntry.js, frontend/src/components/PersonenList.js
Get Personen auf studoo/personen
=> Person feat mo

frontend/src/App.js, frontend/src/api/LernvorliebeBO.js, frontend/src/components/AktProfilEntry.js, frontend/src/components/AktuellesProfil.js, frontend/src/components/EineLernvorliebe.js, frontend/src/components/LernvorliebenListEntry.js, frontend/src/components/PersonEntry.js, frontend/src/components/ProfilVorschau.js, frontend/src/components/dialogs/ProfilForm.js, frontend/src/components/dialogs/ProfilLernvorliebenForm.js, frontend/src/components/header/HeaderComplete.js
Profil Form updates both Person and Lernvorliebe
=> User id moritz

frontend/src/components/PersonEntry.js
=> fix: ProfilForm Error fix

frontend/src/App.js, frontend/src/api/ProfilBO.js, frontend/src/components/AktuellesProfil.js, frontend/src/components/EineLernvorliebe.js, frontend/src/components/LernvorliebenListEntry.js, frontend/src/components/PartnerExplorer.js, frontend/src/components/PersonEntry.js, frontend/src/components/ProfilVorschau.js, frontend/src/components/dialogs/ProfilForm.js, frontend/src/components/pages/Registrieren.js, mysql/MySQL_Datenbank_mit_Dump.sql, src/SecurityDecorator.py, src/main.py, src/server/Admin.py, src/server/bo/Profil.py, src/server/db/ProfilMapper.py
Edit Feld bei eigenem Profil und Beschreibungsfeld
=> Edit only on own profile

frontend/src/components/AusgehendeAnfragenList.js, frontend/src/components/AusgehendeGruppenbeitrittsAnfragenListEntry.js, frontend/src/components/AusgehendeKonversationsAnfragenListEntry.js, frontend/src/components/EingehendeAnfragenList.js, frontend/src/components/EingehendeGruppenbeitrittsAnfragenListEntry.js, frontend/src/components/EingehendeKonversationsAnfragenListEntry.js, frontend/src/components/GruppenAnfragenList.js, frontend/src/components/GruppenAnfragenListEntry.js
Alle Anfragen-Komponenten auskommentiert
=> Andi kommentare
